### ISSUE TITLE
Problems with prison.

### ISSUE THREAD

**Issue by Aaron1988** [BurntJannings/legacy_police#7]
Hi, when a person is in jail, is invincible until the timer ends.

Additionally, after being released from prison, if you try to set a waypoint on the map, the game crashes.

No errors in console, redm says this:

[Window Title]
Error RDR2_b1491.exe+1ABFFEC

[Main Instruction]
RDR2_b1491.exe+1ABFFEC

[Content]
An error at RDR2_b1491.exe+1ABFFEC caused RedM to stop working. A crash report is being uploaded to the RedM developers.

Legacy crash hash: yankee-grey-fillet

[^] Nascondi dettagli  [Save information] [Chiudi]

[Expanded Information]
Crash signature: RDR2_b1491.exe+1ABFFEC
Report ID: ... [uploading]
You can press Ctrl-C to copy this message and paste it elsewhere.

**Comment by LYRYCAL** [comment]
> **Additionally, after being released from prison, if you try to set a waypoint on the map, the game crashes.**
> 

Yeah it happens to me too.

**Comment by BurntJannings** [comment]
This has been fixed a while back now
